version: "3.7"
services:

## --------------------------- IMPA AI --------------------------- ##
  impa-ai:
    image: impa365/impa-ai:0.60.0 # Exemplo: seuusuario/impa-ai-app:latest
    ports:
      # A porta 3000 é exposta internamente para o Traefik, não diretamente para o host.
      # O Traefik cuidará do acesso externo nas portas 80/443.
      # - "{{APP_PORT}}:3000" # Esta linha pode ser removida se o Traefik for o único ponto de entrada.
                               # Ou mantida para acesso direto durante a depuração, se necessário, 
                               # mas garanta que APP_PORT seja diferente das portas do Traefik.
                               # Para uma configuração típica do Traefik, o mapeamento direto de portas é frequentemente omitido.
    networks:
      - ImpaServer
    environment:
      # Configuração do Supabase
      - NEXT_PUBLIC_SUPABASE_URL={{SUPABASE_URL}} # Exemplo: https://seu-projeto-ref.supabase.co
      - NEXT_PUBLIC_SUPABASE_ANON_KEY={{SUPABASE_ANON_KEY}} # Exemplo: sua-chave-anon-supabase
      
      # Configuração do NextAuth
      # IMPORTANTE: NEXTAUTH_URL deve ser a URL pública gerenciada pelo Traefik
      - NEXTAUTH_URL=https://{{APP_DOMAIN}} # Exemplo: https://app.seusite.com
      - NEXTAUTH_SECRET={{NEXTAUTH_SECRET}} # Um segredo forte para o NextAuth
      
      # Chaves de Aplicação Personalizadas
      - CUSTOM_KEY={{CUSTOM_KEY}} # Valor da sua chave personalizada

      # Ambiente da Aplicação
      - NODE_ENV=production
      
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "2"
          memory: 2048M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        # Define o roteador HTTP para o impa-ai
        - "traefik.http.routers.impa_ai_router.rule=Host(`{{APP_DOMAIN}}`)" # Exemplo: app.seusite.com
        - "traefik.http.routers.impa_ai_router.entrypoints=websecure"
        - "traefik.http.routers.impa_ai_router.tls=true"
        - "traefik.http.routers.impa_ai_router.tls.certresolver=letsencryptresolver"
        # Define o serviço para o impa-ai
        - "traefik.http.services.impa_ai_service.loadbalancer.server.port=3000" # Porta interna da aplicação Next.js
        - "traefik.http.services.impa_ai_service.loadbalancer.passHostHeader=true"
        # Vincula o roteador ao serviço
        - "traefik.http.routers.impa_ai_router.service=impa_ai_service"
        # Especifica a rede Docker que o Traefik deve usar para se conectar a este serviço
        - "traefik.docker.network=ImpaServer"

## --------------------------- Networks --------------------------- ##
# Garanta que esta rede seja criada no Portainer ou Docker Swarm antecipadamente
# Exemplo: docker network create --driver overlay ImpaServer
networks:
  ImpaServer:
    external: true
    name: ImpaServer
