version: "3.7"
services:

## --------------------------- IMPA AI Application --------------------------- ##

  impa-ai:
    image: {{DOCKER_IMAGE}}
    
    networks:
      - ImpaServer

    ports:
      - "{{APP_PORT}}:3000"

    environment:
      # Supabase Configuration
      - SUPABASE_URL=https://supa.impa365.com
      - NEXT_PUBLIC_SUPABASE_URL=https://supa.impa365.com
      - SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.ewogICJyb2xlIjogImFub24iLAogICJpc3MiOiAic3VwYWJhc2UiLAogICJpYXQiOiAxNzE1MDUwODAwLAogICJleHAiOiAxODcyODE3MjAwCn0.cVmHXTXMMB09PuXEMevVuGxV5_ZR4yJly6pF0uab7fA
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.ewogICJyb2xlIjogImFub24iLAogICJpc3MiOiAic3VwYWJhc2UiLAogICJpYXQiOiAxNzE1MDUwODAwLAogICJleHAiOiAxODcyODE3MjAwCn0.cVmHXTXMMB09PuXEMevVuGxV5_ZR4yJly6pF0uab7fA
      - SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.ewogICJyb2xlIjogInNlcnZpY2Vfcm9sZSIsCiAgImlzcyI6ICJzdXBhYmFzZSIsCiAgImlhdCI6IDE3MTUwNTA4MDAsCiAgImV4cCI6IDE4NzI4MTcyMDAKfQ.YjqF5C_V-na4rZuMYK9QcddvBnpJpynhKeBefNhumgc
      - SUPABASE_JWT_SECRET=7bf43f2f0d44979abefa9a8c062261f5d4c86aa7
      - SUPABASE_SCHEMA=impaai
      
      # Application Security
      - NEXTAUTH_URL={{NEXTAUTH_URL}}
      - NEXTAUTH_SECRET=7bf43f2f0d44979abefa9a8c062261f5d4c86aa7
      
      # Environment
      - NODE_ENV=production

    volumes:
      - app_uploads:/app/uploads

    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "2"
          memory: 2048M

## --------------------------- Volumes --------------------------- ##

volumes:
  app_uploads:
    external: true
    name: impa_uploads

## --------------------------- Networks --------------------------- ##

networks:
  ImpaServer:
    external: true
    name: ImpaServer
