version: "3.7"
services:

## --------------------------- PostgreSQL --------------------------- ##

  postgres:
    image: postgres:14
    
    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - ImpaServer

    ports:
      - "5432:5432"

    environment:
      - POSTGRES_DB=impa_ai
      - POSTGRES_USER=impa_user
      - POSTGRES_PASSWORD={{POSTGRES_PASSWORD}}
      - PG_MAX_CONNECTIONS=500

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U impa_user -d impa_ai"]
      interval: 30s
      timeout: 10s
      retries: 3

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M

## --------------------------- IMPA AI Application --------------------------- ##

  impa-ai:
    image: {{DOCKER_IMAGE}}
    
    depends_on:
      - postgres

    networks:
      - ImpaServer

    ports:
      - "{{APP_PORT}}:3000"

    environment:
      # Database
      - DATABASE_URL=postgresql://impa_user:{{POSTGRES_PASSWORD}}@postgres:5432/impa_ai
      - POSTGRES_URL=postgresql://impa_user:{{POSTGRES_PASSWORD}}@postgres:5432/impa_ai
      - POSTGRES_PRISMA_URL=postgresql://impa_user:{{POSTGRES_PASSWORD}}@postgres:5432/impa_ai?pgbouncer=true&connect_timeout=15
      - POSTGRES_URL_NON_POOLING=postgresql://impa_user:{{POSTGRES_PASSWORD}}@postgres:5432/impa_ai
      - POSTGRES_USER=impa_user
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD={{POSTGRES_PASSWORD}}
      - POSTGRES_DATABASE=impa_ai
      
      # Supabase
      - SUPABASE_URL={{SUPABASE_URL}}
      - NEXT_PUBLIC_SUPABASE_URL={{SUPABASE_URL}}
      - SUPABASE_ANON_KEY={{SUPABASE_ANON_KEY}}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY={{SUPABASE_ANON_KEY}}
      - SUPABASE_SERVICE_ROLE_KEY={{SUPABASE_SERVICE_ROLE_KEY}}
      - SUPABASE_JWT_SECRET={{SUPABASE_JWT_SECRET}}
      
      # Application
      - NEXTAUTH_URL={{NEXTAUTH_URL}}
      - NEXTAUTH_SECRET={{NEXTAUTH_SECRET}}
      - NODE_ENV=production

    volumes:
      - app_uploads:/app/uploads

    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "2"
          memory: 2048M

## --------------------------- Volumes --------------------------- ##

volumes:
  postgres_data:
    external: true
    name: postgres_data
  app_uploads:
    external: true
    name: impa_uploads

## --------------------------- Networks --------------------------- ##

networks:
  ImpaServer:
    external: true
    name: ImpaServer
