version: "3.7"
services:

## --------------------------- PostgreSQL --------------------------- ##

  postgres:
    image: postgres:14
    
    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - ImpaServer

    ports:
      - "5432:5432"

    environment:
      - POSTGRES_DB={{POSTGRES_DATABASE}}
      - POSTGRES_USER={{POSTGRES_USER}}
      - POSTGRES_PASSWORD={{POSTGRES_PASSWORD}}
      - PG_MAX_CONNECTIONS=500

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U {{POSTGRES_USER}} -d {{POSTGRES_DATABASE}}"]
      interval: 30s
      timeout: 10s
      retries: 3

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M

## --------------------------- IMPA AI Application --------------------------- ##

  impa-ai:
    image: {{DOCKER_IMAGE}}
    
    depends_on:
      - postgres

    networks:
      - ImpaServer

    ports:
      - "{{APP_PORT}}:3000"

    environment:
      # Database Configuration
      - DATABASE_URL=postgresql://{{POSTGRES_USER}}:{{POSTGRES_PASSWORD}}@postgres:5432/{{POSTGRES_DATABASE}}?schema={{POSTGRES_SCHEMA}}
      - POSTGRES_URL=postgresql://{{POSTGRES_USER}}:{{POSTGRES_PASSWORD}}@postgres:5432/{{POSTGRES_DATABASE}}?schema={{POSTGRES_SCHEMA}}
      - POSTGRES_PRISMA_URL=postgresql://{{POSTGRES_USER}}:{{POSTGRES_PASSWORD}}@postgres:5432/{{POSTGRES_DATABASE}}?schema={{POSTGRES_SCHEMA}}&pgbouncer=true&connect_timeout=15
      - POSTGRES_URL_NON_POOLING=postgresql://{{POSTGRES_USER}}:{{POSTGRES_PASSWORD}}@postgres:5432/{{POSTGRES_DATABASE}}?schema={{POSTGRES_SCHEMA}}
      - POSTGRES_USER={{POSTGRES_USER}}
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD={{POSTGRES_PASSWORD}}
      - POSTGRES_DATABASE={{POSTGRES_DATABASE}}
      
      # Supabase Configuration (Obrigat처rias)
      - SUPABASE_URL={{SUPABASE_URL}}
      - NEXT_PUBLIC_SUPABASE_URL={{SUPABASE_URL}}
      - SUPABASE_ANON_KEY={{SUPABASE_ANON_KEY}}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY={{SUPABASE_ANON_KEY}}
      
      # Supabase Configuration (Opcionais - deixe vazio se n찾o usar)
      - SUPABASE_SERVICE_ROLE_KEY={{SUPABASE_SERVICE_ROLE_KEY}}
      - SUPABASE_JWT_SECRET={{SUPABASE_JWT_SECRET}}
      
      # Application Security (Obrigat처rio para sess천es)
      - NEXTAUTH_URL={{NEXTAUTH_URL}}
      - NEXTAUTH_SECRET={{NEXTAUTH_SECRET}}
      
      # Environment
      - NODE_ENV=production

    volumes:
      - app_uploads:/app/uploads

    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "2"
          memory: 2048M

## --------------------------- Volumes --------------------------- ##

volumes:
  postgres_data:
    external: true
    name: postgres_data
  app_uploads:
    external: true
    name: impa_uploads

## --------------------------- Networks --------------------------- ##

networks:
  ImpaServer:
    external: true
    name: ImpaServer
