-- Garante que o esquema 'impaai' exista
CREATE SCHEMA IF NOT EXISTS impaai;

-- =========================================================================
-- Definição do Tipo ENUM 'tipo_midia' no esquema 'impaai'
-- Removido 'IF NOT EXISTS' de CREATE TYPE, adicionado DROP TYPE IF EXISTS
-- =========================================================================
DROP TYPE IF EXISTS impaai.tipo_midia CASCADE; -- Adicionado: Remove o tipo se existir (e suas dependências como colunas)
CREATE TYPE impaai.tipo_midia AS ENUM (      -- Removido 'IF NOT EXISTS'
    'text',
    'image',
    'video',
    'audio',
    'document'
);

-- =========================================================================
-- Definição da Tabela impaai.whatsapp_connections (DEPENDÊNCIA)
-- Cria a tabela apenas se ela ainda não existir
-- =========================================================================
CREATE TABLE IF NOT EXISTS impaai.whatsapp_connections (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    connection_status TEXT
);

-- =========================================================================
-- Definição da Tabela impaai.lead_folow24hs
-- =========================================================================
CREATE TABLE IF NOT EXISTS impaai.lead_folow24hs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "whatsappConection" UUID NOT NULL,
    "remoteJid" TEXT NULL,
    dia NUMERIC NULL,
    "updated_at" timestamptz,

    CONSTRAINT lead_folow24hs_pkey PRIMARY KEY (id),
    CONSTRAINT lead_folow24hs_whatsappConection_fkey
        FOREIGN KEY ("whatsappConection") REFERENCES impaai.whatsapp_connections (id) ON DELETE CASCADE
);

-- =========================================================================
-- Definição da Tabela impaai."folowUp24hs_mensagem"
-- =========================================================================
CREATE TABLE IF NOT EXISTS impaai."folowUp24hs_mensagem" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    whatsapp_conenections_id UUID NOT NULL,
    tentativa_dia NUMERIC NULL,
    tipo_mensagem impaai.tipo_midia NULL,
    mensagem TEXT NULL,
    link TEXT NULL,

    CONSTRAINT folowUp24hs_mensagem_impaai_pkey PRIMARY KEY (id),
    CONSTRAINT folowUp24hs_mensagem_impaai_whatsapp_conenections_id_fkey
        FOREIGN KEY (whatsapp_conenections_id) REFERENCES impaai.whatsapp_connections (id) ON DELETE CASCADE,

    CONSTRAINT chk_link_required CHECK (
        (
            (tipo_mensagem = 'text'::impaai.tipo_midia) AND (link IS NULL)
        ) OR (
            (tipo_mensagem <> 'text'::impaai.tipo_midia) AND (link IS NOT NULL)
        )
    ),

    CONSTRAINT chk_mensagem_content_rules CHECK (
        (
            (tipo_mensagem = 'text'::impaai.tipo_midia) AND (mensagem IS NOT NULL)
        ) OR (
            (tipo_mensagem = 'audio'::impaai.tipo_midia) AND (mensagem IS NULL)
        ) OR (
            tipo_mensagem = ANY (
                ARRAY[
                    'video'::impaai.tipo_midia,
                    'document'::impaai.tipo_midia,
                    'image'::impaai.tipo_midia
                ]
            )
        )
    )
);

-- =========================================================================
-- (Opcional) Adicionar a coluna 'codigo_hash' e seu trigger
-- =========================================================================
/*
ALTER TABLE impaai."folowUp24hs_mensagem"
ADD COLUMN codigo_hash TEXT;

CREATE OR REPLACE FUNCTION impaai.generate_impa365_unique_hash()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.codigo_hash IS NULL OR NEW.codigo_hash = '' THEN
        NEW.codigo_hash := 'impa365hash-' || gen_random_uuid();
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_generate_impa365_hash_impaai
BEFORE INSERT OR UPDATE ON impaai."folowUp24hs_mensagem"
FOR EACH ROW
EXECUTE FUNCTION impaai.generate_impa365_unique_hash();
*/